import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";

import HeaderBlock from "@/components/block/header.block";
import { cn } from "@/lib/utils";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Decision App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          jost.className,
          "relative container max-w-screen-lg h-dvh antialiased "
        )}
      >
        <HeaderBlock />
        {children}
      </body>
    </html>
  );
}
